name: Generate snake

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: surajgariya00
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg
      - uses: actions/checkout@v4
      - name: Commit snake
        run: |
          mkdir -p assets
          cp dist/snake.svg assets/snake.svg || true
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/snake.svg
            git commit -m "chore: update snake"
            git push
          fi
